import { Head } from '@inertiajs/react';
import { Layers3, Pencil, Plus } from 'lucide-react';
import { useState } from 'react';
import { CourseMaterialDialog } from '@/components/admin/course-material-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

type Material = { id: number; course_id: number; title: string; description: string | null; position: number; is_published: boolean; contents_count: number; course: { title: string } };
type Course = { id: number; title: string };
type Pagination = { data: Material[]; current_page: number; last_page: number; prev_page_url: string | null; next_page_url: string | null };

export default function CourseMaterialsIndex({ materials, courses }: { materials: Pagination; courses: Course[] }) {
    const [selected, setSelected] = useState<Material | null>(null); const [open, setOpen] = useState(false); const openForm = (material: Material | null) => { setSelected(material); setOpen(true); }; const setFormOpen = (nextOpen: boolean) => { setOpen(nextOpen); if (!nextOpen) setSelected(null); };
    return <><Head title="Course Materials" /><div className="space-y-6 p-4 md:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Curriculum</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Course Materials</h1><p className="text-sm text-muted-foreground">Manage the modules that structure each course.</p></div><Button onClick={() => openForm(null)}><Plus /> Add material</Button></div><div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-180 text-left text-sm"><thead className="border-b bg-muted/40"><tr><th className="px-5 py-3">Material</th><th>Course</th><th>Contents</th><th>Status</th><th>Position</th><th className="text-right">Action</th></tr></thead><tbody className="divide-y">{materials.data.map((material) => <tr key={material.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-primary/10 p-2 text-primary"><Layers3 className="size-4" /></div><div><p className="font-medium">{material.title}</p><p className="text-xs text-muted-foreground">{material.description || 'No description'}</p></div></div></td><td>{material.course.title}</td><td>{material.contents_count}</td><td><Badge variant={material.is_published ? 'secondary' : 'outline'}>{material.is_published ? 'Published' : 'Draft'}</Badge></td><td>{material.position}</td><td className="px-5 text-right"><Button variant="outline" size="sm" onClick={() => openForm(material)}><Pencil /> Edit</Button></td></tr>)}</tbody></table></div>{materials.data.length === 0 && <div className="px-6 py-16 text-center"><Layers3 className="mx-auto size-10 text-muted-foreground" /><h2 className="mt-4 font-semibold">No course materials</h2><p className="mt-1 text-sm text-muted-foreground">Create the first material for a course.</p></div>}{materials.last_page > 1 && <div className="flex items-center justify-between border-t px-5 py-4 text-sm"><span className="text-muted-foreground">Page {materials.current_page} of {materials.last_page}</span><div className="flex gap-2"><Button asChild variant="outline" size="sm" disabled={!materials.prev_page_url}><a href={materials.prev_page_url ?? '#'}>Previous</a></Button><Button asChild variant="outline" size="sm" disabled={!materials.next_page_url}><a href={materials.next_page_url ?? '#'}>Next</a></Button></div></div>}</div></div>{open && <CourseMaterialDialog material={selected} courses={courses} open={open} onOpenChange={setFormOpen} />}</>;
}
