import { Head, Link, usePage } from '@inertiajs/react';
import { ArrowRight, BookOpen, CalendarDays, ChevronDown, Clock3, Headphones, Instagram, Linkedin, MonitorPlay, Quote, Search, Star, UserRound, UsersRound, Video, Youtube } from 'lucide-react';
import { dashboard, login, register } from '@/routes';

const categories = [
    ['For The Kids', 'Kids Class Online', '/welcome/class-for-kids.png'],
    ['For Summertime', 'Summer Camp Online', '/welcome/class-for-summertime.png'],
    ['For Adult Person', 'Adult Class Online', '/welcome/class-for-adults.png'],
];

const popularCourses = [
    ['Technology', 'Full-Stack Web Development', 'Build modern web applications through hands-on projects and live mentorship.', 'Alex Carter', 'Senior Software Engineer', '12 Weeks', '4.9', '2.1K', 'course-tech', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80'],
    ['Design', 'UI/UX Design Fundamentals', 'Learn how to design intuitive digital products and build a professional portfolio.', 'Marcus Chen', 'Product Designer', '8 Weeks', '4.8', '1.9K', 'course-design', 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=900&q=80'],
    ['Marketing', 'Digital Marketing Essentials', 'Master content, social media, advertising, and campaign strategy.', 'Sophia Lee', 'Digital Marketing Strategist', '6 Weeks', '4.9', '3.2K', 'course-marketing', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80'],
];
const instructors = [['Alex Carter', 'Senior Software Engineer', 'Web Development', 'instructor-alex', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80'], ['Sophia Lee', 'Digital Marketing Strategist', 'Digital Marketing', 'instructor-sophia', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=80'], ['Marcus Chen', 'Product Designer', 'UI/UX Design', 'instructor-marcus', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80']];
const testimonials = [['The live classes are amazing! The instructors explain everything clearly and the community is so supportive.', 'Jessica Taylor', 'Web Developer', 'testimonial-jessica', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80'], ['I gained practical skills and confidence to switch careers. The learning experience is top-notch!', 'Michael Brown', 'Marketing Specialist', 'testimonial-michael', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80'], ['High-quality content, great instructors, and very flexible schedule. Highly recommended!', 'Priya Sharma', 'UX Designer', 'testimonial-priya', 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=300&q=80']];

export default function Welcome() {
    const { auth } = usePage().props;
    return <>
        <Head title="Eduo - Live Online Training" />
        <div className="edu-page">
            <header className="edu-header">
                <Link href="/" className="edu-brand" aria-label="Eduo home"><span className="edu-brand-mark"><BookOpen size={27} /></span>Eduo</Link>
                <button className="edu-category-button" type="button">Category <ChevronDown size={13} /></button>
                <label className="edu-search"><Search size={17} /><input type="search" placeholder="Search" aria-label="Search courses" /></label>
                <nav className="edu-nav" aria-label="Main navigation">{['Home', 'About Us', 'Courses', 'Pages', 'Blog'].map((item) => <a href={`#${item.toLowerCase().replace(' ', '-')}`} key={item}>{item} <ChevronDown size={12} /></a>)}<a href="#contact">Contact Us</a></nav>
                <button className="edu-language" type="button">English <ChevronDown size={12} /></button>
                <Link className="edu-header-cta" href={register()}>Get Started <ArrowRight size={16} /></Link>
                <Link className="edu-user-button" href={auth.user ? dashboard() : login()} aria-label={auth.user ? 'Open dashboard' : 'Log in'}><UserRound size={17} /></Link>
            </header>
            <main>
                <section className="edu-hero" id="home">
                    <img className="edu-hero-image" src="/welcome/hero-online-training.png" alt="Expert instructor teaching a live online class" />
                    <h1 className="edu-visually-hidden">Our Live Online Training Is Taught By Expert Instructors</h1>
                    <Link className="edu-hero-hotspot" href="#classes" aria-label="Browse our course catalog" />
                </section>                <section className="edu-benefits" aria-label="Eduo benefits">
                    <div><span className="edu-icon-box"><CalendarDays /></span><div><h3>Class Schedule</h3><p>Eduo provides engaging instructor led content for people everywhere and of all ages without having to leave the house.</p></div></div>
                    <div><span className="edu-icon-box"><MonitorPlay /></span><div><h3>Interactive Led Online Advantage</h3><p>Eduo provides engaging instructor led content for people everywhere and of all ages without having to leave the house.</p></div></div>
                    <div><span className="edu-icon-box"><UsersRound /></span><div><h3>100% Satisfaction Guaranteed</h3><p>Eduo provides engaging instructor led content for people everywhere and of all ages without having to leave the house.</p></div></div>
                </section>
                <section className="edu-section" id="classes"><div className="edu-section-heading"><h2>Join Our 780+ Live Online<br />Classes For Student</h2><a href="#classes">View Online Classes <ArrowRight size={20} /></a></div><div className="edu-category-grid">{categories.map(([title, link, image]) => <article className="edu-category-card" key={title}><img className="edu-category-image" src={image} alt={title} /><h3>{title}</h3><p>Eduo provides engaging instructor led content for people everywhere and of all ages, without.</p><a href="#contact">{link} <ArrowRight size={17} /></a></article>)}</div></section>
                <section className="edu-section edu-experience" id="about-us"><div className="edu-video-collage" role="img" aria-label="Interactive online class"><img src="/welcome/interactive-video-class.png" alt="Students and instructors in an interactive online class" /></div><div className="edu-experience-copy"><h2>We Want To Give Students A<br />Great Interactive Experience!</h2><p>Eduo provides engaging instructor led content for people everywhere and of all ages, without having to leave the house.</p><div className="edu-feature"><span className="edu-icon-box"><Headphones /></span><div><h3>Instant Help</h3><p>Eduo provides engaging instructor led content for people everywhere and of all ages.</p></div></div><div className="edu-feature"><span className="edu-icon-box"><BookOpen /></span><div><h3>Unlimited Learning</h3><p>Eduo provides engaging instructor led content for people everywhere and of all ages.</p></div></div><div className="edu-stats"><div><strong>13 Million+</strong><span>Hours of Live Interactive</span></div><div><strong>3000+</strong><span>Our subject expertise</span></div></div></div><a className="edu-more-link" href="#contact">More About Eduo <ArrowRight size={18} /></a></section>
                <section className="edu-continuation">
    <section className="edu-section edu-popular" id="courses"><div className="edu-continuation-heading"><div><span className="edu-section-kicker">POPULAR CLASSES</span><h2>Join Our Online Classes</h2><p>Learn practical skills through live, instructor-led classes designed to help you grow with confidence.</p></div><a href="#courses">View All Classes <ArrowRight size={20} /></a></div><div className="edu-course-grid">{popularCourses.map(([category, title, copy, instructor, role, duration, rating, reviews, variant, imageUrl]) => <article className={`edu-course-card ${variant}`} key={title}><div className="edu-course-art"><img src={imageUrl} alt={`${title} course`} loading="lazy" referrerPolicy="no-referrer" /><span>{category}</span></div><div className="edu-course-body"><h3>{title}</h3><p>{copy}</p><div className="edu-course-meta"><span className="edu-mini-avatar" /><div><strong>{instructor}</strong><small>{role}</small></div><div className="edu-rating"><Star size={15} fill="currentColor" /><strong>{rating}</strong><small>({reviews})</small></div></div><div className="edu-course-footer"><span><Clock3 size={16} />{duration}</span><span><Video size={16} />Live Online</span><a href="#contact">View Class <ArrowRight size={16} /></a></div></div></article>)}</div></section>
    <section className="edu-instructors"><div className="edu-section edu-instructor-inner"><div className="edu-continuation-heading"><div><span className="edu-section-kicker">LEARN FROM INDUSTRY EXPERTS</span><h2>Learn From People Who Know The Industry</h2><p>Our instructors combine real-world experience with practical teaching to help you gain skills you can actually use.</p></div><a href="#about-us">View All Instructors <ArrowRight size={20} /></a></div><div className="edu-instructor-grid">{instructors.map(([name, role, specialty, variant, imageUrl]) => <article className="edu-instructor-card" key={name}><div className={`edu-instructor-avatar ${variant}`}><img src={imageUrl} alt={name} loading="lazy" referrerPolicy="no-referrer" /></div><div><h3>{name}</h3><p>{role}</p><span>{specialty}</span><div className="edu-socials"><Linkedin size={16} fill="currentColor" /><span>♥</span><Youtube size={16} fill="currentColor" /></div></div></article>)}</div></div></section>
    <section className="edu-section edu-testimonials"><div className="edu-continuation-heading"><div><span className="edu-section-kicker">STUDENT SUCCESS</span><h2>What Our Students Say</h2></div><p>Real stories from learners who have transformed their careers.</p></div><div className="edu-testimonial-grid">{testimonials.map(([quote, name, role, variant, imageUrl]) => <article className="edu-testimonial-card" key={name}><Quote size={30} fill="currentColor" /><p>{quote}</p><div><span className={`edu-mini-avatar ${variant}`}><img src={imageUrl} alt={name} loading="lazy" referrerPolicy="no-referrer" /></span><strong>{name}<small>{role}</small></strong><span className="edu-testimonial-stars">★★★★★</span></div></article>)}</div></section>
    <section className="edu-section edu-cta"><div><span className="edu-section-kicker">START LEARNING TODAY</span><h2>Invest In Your Future With Eduo.</h2><p>Join thousands of learners and take the next step toward your goals.</p></div><div className="edu-cta-action"><Link href={register()}>Get Started <ArrowRight size={17} /></Link><small>No credit card required</small></div><img className="edu-cta-person" src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=700&q=80" alt="Student ready to learn" loading="eager" referrerPolicy="no-referrer" /></section>
    <section className="edu-section edu-brands"><span className="edu-section-kicker">TRUSTED BY LEARNERS AT</span><div><strong>Google</strong><strong>▦ Microsoft</strong><strong>◊ airbnb</strong><strong>◉ Spotify</strong><strong>♙ shopify</strong><strong>▣ Notion</strong></div></section>
    <footer className="edu-footer"><div className="edu-footer-brand"><Link href="/" className="edu-brand"><span className="edu-brand-mark"><BookOpen size={28} /></span>Eduo</Link><p>Skills for a brighter tomorrow.</p><div className="edu-socials"><Linkedin size={16} /><span>♥</span><Instagram size={16} /><Youtube size={16} /></div><small>© 2026 Eduo. All rights reserved.</small></div><div><h3>Quick Links</h3>{['Home', 'About Us', 'Courses', 'Blog', 'Contact'].map((item) => <a href={`#${item.toLowerCase().replace(' ', '-')}`} key={item}>{item}</a>)}</div><div><h3>Popular Courses</h3>{['Web Development', 'Digital Marketing', 'UI/UX Design', 'Business', 'Personal Development'].map((item) => <a href="#courses" key={item}>{item}</a>)}</div><div className="edu-footer-newsletter"><h3>Subscribe to Our Newsletter</h3><p>Get the latest courses, tips, and updates.</p><div><input type="email" placeholder="Your email address" aria-label="Email address" /><button type="button">Subscribe</button></div><small>Making education accessible for a brighter tomorrow. <b>♥</b></small></div></footer>
</section>
            </main>
        </div>
    </>;
}





