import { Head } from '@inertiajs/react';
import { FileText, Pencil, Plus, Video } from 'lucide-react';
import { useState } from 'react';
import { LearningContentDialog } from '@/components/admin/learning-content-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

type MaterialOption = { id: number; title: string; course: { title: string } };
type Content = { id: number; course_material_id: number; type: 'video' | 'textbook'; title: string; description: string | null; position: number; youtube_url: string | null; textbook_content: string | null; attachment_url: string | null; is_published: boolean; material: { title: string; course: { title: string } } };
type Pagination = { data: Content[]; current_page: number; last_page: number; prev_page_url: string | null; next_page_url: string | null };

export default function LearningContentsIndex({ contents, materials }: { contents: Pagination; materials: MaterialOption[] }) {
    const [selected, setSelected] = useState<Content | null>(null); const [open, setOpen] = useState(false); const openForm = (content: Content | null) => { setSelected(content); setOpen(true); }; const setFormOpen = (nextOpen: boolean) => { setOpen(nextOpen); if (!nextOpen) setSelected(null); };
    return <><Head title="Learning Contents" /><div className="space-y-6 p-4 md:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Curriculum</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Learning Contents</h1><p className="text-sm text-muted-foreground">Manage video lessons and textbook chapters.</p></div><Button onClick={() => openForm(null)}><Plus /> Add content</Button></div><div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-220 text-left text-sm"><thead className="border-b bg-muted/40"><tr><th className="px-5 py-3">Content</th><th>Course / Material</th><th>Type</th><th>Status</th><th>Position</th><th className="text-right">Action</th></tr></thead><tbody className="divide-y">{contents.data.map((content) => <tr key={content.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-primary/10 p-2 text-primary">{content.type === 'video' ? <Video className="size-4" /> : <FileText className="size-4" />}</div><div><p className="font-medium">{content.title}</p><p className="text-xs text-muted-foreground">{content.description || 'No description'}</p></div></div></td><td><p>{content.material.course.title}</p><p className="text-xs text-muted-foreground">{content.material.title}</p></td><td className="capitalize">{content.type}</td><td><Badge variant={content.is_published ? 'secondary' : 'outline'}>{content.is_published ? 'Published' : 'Draft'}</Badge></td><td>{content.position}</td><td className="px-5 text-right"><Button variant="outline" size="sm" onClick={() => openForm(content)}><Pencil /> Edit</Button></td></tr>)}</tbody></table></div>{contents.data.length === 0 && <div className="px-6 py-16 text-center"><FileText className="mx-auto size-10 text-muted-foreground" /><h2 className="mt-4 font-semibold">No learning contents</h2><p className="mt-1 text-sm text-muted-foreground">Create the first lesson or textbook chapter.</p></div>}{contents.last_page > 1 && <div className="flex items-center justify-between border-t px-5 py-4 text-sm"><span className="text-muted-foreground">Page {contents.current_page} of {contents.last_page}</span><div className="flex gap-2"><Button asChild variant="outline" size="sm" disabled={!contents.prev_page_url}><a href={contents.prev_page_url ?? '#'}>Previous</a></Button><Button asChild variant="outline" size="sm" disabled={!contents.next_page_url}><a href={contents.next_page_url ?? '#'}>Next</a></Button></div></div>}</div></div>{open && <LearningContentDialog content={selected} materials={materials} open={open} onOpenChange={setFormOpen} />}</>;
}
