import { Link, usePage } from '@inertiajs/react';
import { BookOpen, ChartNoAxesCombined, GraduationCap, LayoutDashboard, LogOut, Settings } from 'lucide-react';
import type { CSSProperties } from 'react';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import type { Auth } from '@/types/auth';

export default function StudentLayout({ children }: { children: React.ReactNode }) {
    const { auth } = usePage<{ auth: Auth }>().props;
    const initials = auth.user.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
    return <SidebarProvider style={{ '--sidebar-width': 'calc(var(--spacing) * 72)', '--header-height': 'calc(var(--spacing) * 12)' } as CSSProperties}><Sidebar variant="inset" collapsible="offcanvas"><SidebarHeader><SidebarMenu><SidebarMenuItem><SidebarMenuButton asChild className="data-[slot=sidebar-menu-button]:p-1.5!"><Link href="/dashboard"><GraduationCap className="size-5!" /><span className="text-base font-semibold">Edoo Learning</span></Link></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupContent className="flex flex-col gap-2"><SidebarMenu><SidebarMenuItem className="flex items-center gap-2"><SidebarMenuButton className="min-w-8 bg-primary text-primary-foreground hover:bg-primary/90 hover:text-primary-foreground"><ChartNoAxesCombined /><span>My learning</span></SidebarMenuButton><Button size="icon" variant="outline" className="size-8"><BookOpen /><span className="sr-only">My courses</span></Button></SidebarMenuItem></SidebarMenu><SidebarMenu><SidebarMenuItem><SidebarMenuButton asChild tooltip="Dashboard"><Link href="/dashboard"><LayoutDashboard /><span>Dashboard</span></Link></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton asChild tooltip="Courses"><Link href="/courses"><BookOpen /><span>Explore courses</span></Link></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroupContent></SidebarGroup><SidebarGroup className="mt-auto"><SidebarGroupContent><SidebarMenu><SidebarMenuItem><SidebarMenuButton><Settings /><span>Settings</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter><SidebarMenu><SidebarMenuItem><SidebarMenuButton size="lg"><Avatar className="size-8 rounded-lg"><AvatarFallback className="rounded-lg">{initials}</AvatarFallback></Avatar><div className="grid flex-1 text-left text-sm leading-tight"><span className="truncate font-medium">{auth.user.name}</span><span className="truncate text-xs text-muted-foreground">{auth.user.email}</span></div><LogOut className="ml-auto size-4" /></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter></Sidebar><SidebarInset><header className="flex h-(--header-height) shrink-0 items-center gap-2 border-b transition-[width,height] ease-linear"><div className="flex w-full items-center gap-1 px-4 lg:gap-2 lg:px-6"><SidebarTrigger className="-ml-1" /><Separator orientation="vertical" className="mx-2 data-[orientation=vertical]:h-4" /><h1 className="text-base font-medium">Student Dashboard</h1></div></header>{children}</SidebarInset></SidebarProvider>;
}
